### ISSUE TITLE
How do I duplicate the code from this blog post in Rust?

### ISSUE THREAD

**Issue by dralley** [luteberget/minisat-rs#2]
https://codingnest.com/modern-sat-solvers-fast-neat-underused-part-1-of-n/

The example code in this blog post uses the standard C++ minisat API, but it doesn't directly correspond to the minisat_rust API.  Notably, the latter seems to be missing an analogue to ```newVar``` and ```mkLit(integer)```.  Am I missing something, or is the bindings simply incomplete?

**Comment by luteberget** [comment]
The integer representation of variable references is not currently exposed through this API, no.   I don't think this style of untyped (i.e. integer) references is worth using, and I expect the possible efficiency gains to be very small, but I am open to any compelling arguments the other way. Instead, you get only opaque literal references for each call to `Solver::new_lit`.

If you want to reference literals by indexing you can build an array of literals instead.  Something like this:

```rust
let matrix = (0..9*9).map(|_| s.new_lit()).collect::Vec<_>();
```

**Comment by dralley** [comment]
What would be the most "ergonomically correct" way to reimplement those code snippets given the existing API?  If you wouldnt mind providing one as an example.

**Comment by luteberget** [comment]
Here is how I would write it. Could you look over the code and check it on some examples to see if it gives correct answers? I could add this example to the README file.

```rust
pub fn solve_sudoku(problem: &str) -> Option<String> {
    // SAT-based Sudoku solver, implemented similarly as in this document:
    // https://codingnest.com/modern-sat-solvers-fast-neat-underused-part-1-of-n/

    use itertools::iproduct;
    use minisat::{symbolic::*, *};

    let mut s = Solver::new();
    let matrix = problem.chars().map(|c| {
        if let Some(i) = c.to_digit(10) {
            Symbolic::new(&mut s, vec![i - 1])
        } else {
            Symbolic::new(&mut s, (0..9).collect())
        }
    }).collect::<Vec<_>>();

    for val in 0..9 {
        // Rule 1: no row contains duplicate numbers
        for x in 0..9 {
            s.assert_at_most_one((0..9).map(|y| matrix[9 * y + x].has_value(&val)));
        }
        // Rule 2: no column contains duplicate numbers
        for y in 0..9 {
            s.assert_at_most_one((0..9).map(|x| matrix[9 * y + x].has_value(&val)));
        }
        // Rule 3: no 3x3 box contains duplicate numbers
        for (box_x, box_y) in iproduct!((0..9).step_by(3), (0..9).step_by(3)) {
            s.assert_at_most_one(
                iproduct!(0..3, 0..3)
                    .map(|(x, y)| matrix[9 * (box_x + x) + (box_y + y)].has_value(&val)),
            );
        }
    }
    
    s.solve().ok().map(|m| {
        matrix.into_iter() 
            .map(|v| format!("{}", m.value(&v) + 1)) 
            .collect()
    })
}   

fn main() {
    println!("{:?}",solve_sudoku(
        "4.....8.5.3..........7......2.....6.....8.4......1.......6.3.7.5..2.....1.4......"
    ));
}
```

**Comment by dralley** [comment]
@luteberget Thank you, that is really helpful!  I will test this later today

**Comment by dralley** [comment]
@luteberget It works great!  Here's what I added:

```
use itertools::iproduct;
use minisat::Solver;
use minisat::symbolic::Symbolic;
use sudoku::Sudoku;

fn main() {
    let puzzle = Sudoku::generate_unique();
    println!("{}", puzzle.display_block());

    let solution = solve_sudoku(&puzzle.to_str_line()).expect("Unable to solve puzzle");
    let solved_puzzle = Sudoku::from_str_line(&solution).expect("Unable to parse puzzle");

    println!("{}", solved_puzzle.display_block());
    assert!(solved_puzzle.is_solved());
}
```

**Comment by luteberget** [comment]
Thanks, I didn't know about the sudoku crate. I added the whole thing to doc comments and readme.
