### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by jacob-greenfield** [luteberget/minisat-rs#3]
I am trying to implement a Rust wrapper around another SAT solver ([CaDiCaL](https://github.com/arminbiere/cadical)) and would like to reuse parts of this crate for it. Would you would be willing to specify an open source license for this project? (MIT, etc.)

**Comment by luteberget** [comment]
Sure, I have added an MIT license text to the repository.

Why do you want to use that specific solver? Is it faster? Maybe a slightly higher-level SAT interface such as this crate should define a SAT solver trait and allow selecting different back-end solvers?

**Comment by jacob-greenfield** [comment]
Thank you for adding the license, I really appreciate your work.

To answer your question, I am choosing CaDiCaL mainly because it's been updated more recently than MiniSat and has become significantly faster. See [this year's SAT race rankings](http://sat-race-2019.ciirc.cvut.cz/index.php?cat=results). The main reason I chose it specifically is that it comes with a simple C interface. For my purposes the tiny performance increase of a Maple-based solver is not worth the difficult work of writing bindings to C++.

Creating a common trait for SAT solvers in Rust with an interchangeable backend sounds like a good idea. I'll see how my wrapper ends up.
